### PR TITLE
Added support for darkmode and placed all CSS in webapp/static/css

### PR DESCRIPTION
**Pull request by VanTekken**
Updated the webapp to add support for darkmode, as well as organized CSS by placing all CSS in the webapp/static/css directory and importing to the base.html template.

### CODE REVIEW

**Comment by VanTekken** [comment]
Please add Hacktoberfest label if accepted 🚀

**Comment by beneyal** [comment]
Nice work!

Before I merge this, I have to ask you to pull the latest changes from the main repo since your branch is not up to date. On a more personal note, I think we can skip the nuke image.

Regarding the label, we don't need it since this repo already has the needed Hacktoberfest labels. If the PR doesn't show in your Hacktoberfest profile page, try to "hard refresh" it in ~15 minutes (it doesn't update in real time).

**Comment by VanTekken** [comment]
> Nice work!
> 
> Before I merge this, I have to ask you to pull the latest changes from the main repo since your branch is not up to date. On a more personal note, I think we can skip the nuke image.
> 
> Regarding the label, we don't need it since this repo already has the needed Hacktoberfest labels. If the PR doesn't show in your Hacktoberfest profile page, try to "hard refresh" it in ~15 minutes (it doesn't update in real time).

Noted, thank you! Trying to revert that example image folder now.

**Comment by VanTekken** [comment]
Sorry for pull request spam, still getting used to this! That image folder has now been reverted and my branch synced 🚀 Is this enough to update my branch to the repo's latest changes?

**Comment by beneyal** [comment]
Yup, your PR is now perfect! Merging it now 🙂

**Pull request merged**
