### PR TITLE
Added simple coloring for ascii

### PR DESCRIPTION
**Pull request by pritindra**
Changed community code and added a simple three-color option for a user to color the converted ASCII image.

### CODE REVIEW

**Comment by beneyal** [comment]
Very nice use of `rich`!

Do you think you can add this option as a command-line option (like `--color`)? That way the users won't have to specify a color every time, but only when they want. For example, `python3 ./community-version.py --color red` will output only a red ASCII art.

**Comment by pritindra** [comment]
Sure. @beneyal. I will work on it next.

**Comment by pritindra** [comment]
Should I close this PR and make another with the additions?

**Comment by beneyal** [comment]
No, you can keep committing to your existing fork and branch and the new commits will show up here 🙂

**Pull request closed without merging**
