### PR TITLE
Added program for saving the ascii image in text file.

### PR DESCRIPTION
**Pull request by dmdbilal**
I've added program for saving the ascii image in text file in a separate file. Also made changes in make_art_python2 so now it can run in python3 without any errors.

### CODE REVIEW

**Comment by tbot1738** [comment]
I guess there is already that feature. Use `git pull upstream master` in case you have not updated your directory since long time

**Comment by dmdbilal** [comment]
> I guess there is already that feature. Use `git pull upstream master` in case you have not updated your directory since long time

I did that before I pushed this PR.

**Comment by beneyal** [comment]
As @tbot1738 said, the save feature already exists: https://github.com/zero-to-mastery/ascii-art-2022/blob/0858ae69e43ca7e2e09a65a98916b2f69243158d/community_version.py#L245-L258

And, as I said in the previous PR, I'd rather not merge the fixed Python 2 file to let others work on it as well in their own fork.

**Comment by dmdbilal** [comment]
Ok it's my fault👍

**Pull request closed without merging**
