### PR TITLE
Fixed double download problem on text art page

### PR DESCRIPTION
**Pull request by TalhaQuddoos**
Problem:
https://user-images.githubusercontent.com/60311647/197251325-e6415b65-85e0-447c-ab62-d7b715396f1b.mp4

Two event listeners were attached to the button, deleted one to fix.

### CODE REVIEW

**Comment by beneyal** [comment]
Do you want to take some time to make sure there is nothing else you want to fix before I merge this? 😂

**Comment by TalhaQuddoos** [comment]
Haha sure, gimme some time :P

**Comment by TalhaQuddoos** [comment]
Fixed another problem I found: Text art box too big.

Planning to add an option for selecting text art background. Should I do it in a new PR or just commit to this?

**Comment by beneyal** [comment]
Commit to this one, please 🙂

**Comment by TalhaQuddoos** [comment]
Done.

**Pull request merged**
